# Generated by Django 4.2 on 2023-05-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminorder',
            name='table',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cheforder',
            name='table',
            field=models.CharField(default='', max_length=50),
        ),
    ]
